routes/web.php
<?php

/**
 * Admin Route/s
 */
Route::group([
    'as' => 'voyager.forms.',
    'prefix' => 'admin/forms/',
    'middleware' => ['web', 'admin.user'],
    'namespace' => '\Pvtl\VoyagerForms\Http\Controllers'
], function () {
    Route::post('sort', ['uses' => "InputController@sort", 'as' => 'sort']);
});

Route::group([
    'as' => 'voyager.enquiries.',
    'prefix' => 'admin/enquiries/',
    'middleware' => ['web', 'admin.user'],
    'namespace' => '\Pvtl\VoyagerForms\Http\Controllers'
], function () {
    Route::get('{id}/file/{fileKey}', ['uses' => "EnquiryController@getFile", 'as' => 'file']);
});


/**
 * Front-end Route/s
 */
Route::group([
    'as' => 'voyager.enquiries.',
    'middleware' => ['web'],
    'namespace' => '\Pvtl\VoyagerForms\Http\Controllers'
], function () {
    Route::post('voyager-forms-submit-enquiry/{id}', ['uses' => "EnquiryController@submit", 'as' => 'submit']);
});

resources/views/email-templates/default.blade.php
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title> --- </title>
    <style>
    /* -------------------------------------
        RESPONSIVE AND MOBILE FRIENDLY STYLES
    ------------------------------------- */
    @media only screen and (max-width: 620px) {
      table[class=body] h1 {
        font-size: 28px !important;
        margin-bottom: 10px !important;
      }
      table[class=body] p,
      table[class=body] ul,
      table[class=body] ol,
      table[class=body] td,
      table[class=body] span,
      table[class=body] a {
        font-size: 16px !important;
      }
      table[class=body] .wrapper,
            table[class=body] .article {
        padding: 10px !important;
      }
      table[class=body] .content {
        padding: 0 !important;
      }
      table[class=body] .container {
        padding: 0 !important;
        width: 100% !important;
      }
      table[class=body] .main {
        border-left-width: 0 !important;
        border-radius: 0 !important;
        border-right-width: 0 !important;
      }
      table[class=body] .btn table {
        width: 100% !important;
      }
      table[class=body] .btn a {
        width: 100% !important;
      }
      table[class=body] .img-responsive {
        height: auto !important;
        max-width: 100% !important;
        width: auto !important;
      }
    }

    /* -------------------------------------
        PRESERVE THESE STYLES IN THE HEAD
    ------------------------------------- */
    @media all {
      .ExternalClass {
        width: 100%;
      }
      .ExternalClass,
      .ExternalClass p,
      .ExternalClass span,
      .ExternalClass font,
      .ExternalClass td,
      .ExternalClass div {
        line-height: 100%;
      }
      .apple-link a {
        color: inherit !important;
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        text-decoration: none !important;
      }
      .btn-primary table td:hover {
        background-color: #34495e !important;
      }
      .btn-primary a:hover {
        background-color: #34495e !important;
        border-color: #34495e !important;
      }
    }
    </style>
  </head>
  <body class="" style="background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
    <table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;">
      <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
        <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;">
          <div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">
            <h2 style="font-family: sans-serif; font-size: 18px; font-weight: bold; margin: 0; Margin-bottom: 15px; margin-left: 20px;">{{ $form->mailfromname }}</h2>

            <!-- START CENTERED WHITE CONTAINER -->
            <table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">
                          Hi there,<br />
                          The following enquiry was submitted through the {{ $form->mailfromname }} website.
                        </p>

                        @include('voyager-forms::enquiries.email')
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>

            <!-- START FOOTER -->
            <div class="footer" style="clear: both; Margin-top: 10px; text-align: center; width: 100%;">
              <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                <tr>
                  <td class="content-block" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                    <span class="apple-link" style="color: #999999; font-size: 12px; text-align: center;">&copy; {{ $form->mailfromname }}</span>. All Rights Reserved.
                  </td>
                </tr>
              </table>
            </div>
            <!-- END FOOTER -->

          <!-- END CENTERED WHITE CONTAINER -->
          </div>
        </td>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
      </tr>
    </table>
  </body>
</html>

resources/views/enquiries/email.blade.php
<table border="0" cellpadding="0" cellspacing="0" class="btn btn-primary" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;">
    <tbody>
        @foreach ($enquiries as $key => $enquiry)
            <tr>
                <th align="left" width="25%" style="font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px; font-weight: bold;">
                    {{ str_replace('_', ' ', $key) }}
                </th>

                <td align="left" style="font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;">
                    {!! nl2br($enquiry) !!}
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/enquiries/view.blade.php
@extends('voyager::master')

@section('page_title', __('voyager::generic.viewing').' '.$dataType->display_name_plural)

@section('page_header')
    <div class="container-fluid">
        <h1 class="page-title">
            <i class="{{ $dataType->icon }}"></i> {{ $dataType->display_name_plural }}
        </h1>
        @include('voyager::multilingual.language-selector')
    </div>
@stop

@section('content')
    <div class="page-content browse container-fluid">
        @include('voyager::alerts')
        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-bordered panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Enquiry</h3>
                    </div> <!-- /.panel-heading -->

                    <table class="table">
                        <tr>
                            <th width="25%">Form ID</th>
                            <td>
                                <a href="{{ route('voyager.forms.edit', $enquiry->form_id) }}">
                                    {{ $enquiry->form_id }} (View)
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <th>Mailed To</th>
                            <td>{{ $enquiry->mailto }}</td>
                        </tr>
                        <tr>
                            <th>From IP Address</th>
                            <td>{{ $enquiry->ip_address }}</td>
                        </tr>
                        <tr>
                            <th>Submitted At</th>
                            <td>{{ $enquiry->created_at }}</td>
                        </tr>
                    </table>
                </div> <!-- /.panel -->
            </div> <!-- /.col -->

            <div class="col-md-8">
                <div class="panel panel-bordered">
                    <div class="panel-heading">
                        <h3 class="panel-title">Submitted Data</h3>
                    </div> <!-- /.panel-heading -->

                    <table class="table">
                        @foreach ($enquiry->data as $key => $value)
                            <tr>
                                <th width="25%">{{ str_replace('_', ' ', $key) }}</th>
                                <td>{!! nl2br($value) !!}</td>
                            </tr>
                        @endforeach
                    </table>
                </div> <!-- /.panel -->
                <div class="panel panel-bordered">
                    <div class="panel-heading">
                        <h3 class="panel-title">Files Attached</h3>
                    </div> <!-- /.panel-heading -->

                    <table class="table">
                        @foreach($files as $file)
                            <tr>
                                <td>
                                    <a href="{{$file['url']}}" target="_blank">{{$file['filename']}}</a>
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div> <!-- /.panel -->
            </div> <!-- /.col -->
        </div> <!-- /.row -->
    </div> <!-- /.page-content -->
@stop

resources/views/forms/edit-add.blade.php
@extends('voyager::master')

@section('page_title', __('voyager::generic.'.(isset($form->id) ? 'edit' : 'add')).' '.$dataType->display_name_singular)

@section('css')
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <style type="text/css">
        /* Remove bottom margins */
        .row > [class*=col-].no-bottom-margin {
            margin-bottom: 0;
        }

        /* Toggle Button */
        .toggle.btn {
            box-shadow: 0 5px 9px -3px rgba(0, 0, 0, 0.2);
            border: 1px solid rgba(0, 0, 0, 0.2) !important;
        }

        /* Make Inputs a 'lil more visible */
        select,
        input[type="text"],
        .panel-body .select2-selection {
            border: 1px solid rgba(0, 0, 0, 0.17)
        }

        /* Reorder */
        .dd .dd-placeholder {
            max-height: 60px;
            margin-bottom: 22px;
        }
        .dd h3.panel-title,
        .dd-dragel h3.panel-title {
            padding-left: 55px;
        }
        .dd-dragel .panel-body {
            display: none !important;
        }
        .order-handle {
            z-index: 1;
            position: absolute;
            padding: 20px 15px 19px;
            background: rgba(255,255,255,0.2);
            font-size: 15px;
            color: #fff;
            line-height: 20px;
            box-shadow: inset -2px 0px 2px rgba(0,0,0,0.1);
            cursor: move;
        }
    </style>
@stop

@section('page_header')
    <h1 class="page-title">
        <i class="{{ $dataType->icon }}"></i>
        {{ __('voyager::generic.'.(isset($form->id) ? 'edit' : 'add')).' '.$dataType->display_name_singular }}
    </h1>
@stop

@section('content')
    <div class="page-content edit-add container-fluid">
        @include('voyager::alerts')

        <div class="row">
            <div class="col-md-4">
                <div class="panel">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="voyager-info-circled"></i> Form Details</h3>
                    </div> <!-- /.panel-heading -->

                    <div class="panel-body">
                        <form
                            role="form"
                            action="@if (isset($form->id))
                            {{ route('voyager.'.$dataType->slug.'.update', $form->id) }}
                            @else
                            {{ route('voyager.'.$dataType->slug.'.store') }}
                            @endif"
                            method="POST"
                            enctype="multipart/form-data">

                            {{ csrf_field() }}

                            @if (isset($form->id))
                                {{ method_field("PUT") }}
                            @endif
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input name="title" class="form-control" type="text"
                                       @if (isset($form->title)) value="{{ $form->title }}" @endif required>
                            </div>

                            @if (isset($form->id))
                                <div class="form-group">
                                    <label for="shortcode">Shortcode
                                        <small>(Paste this code into a text field to display the form)</small>
                                    </label>
                                    <input
                                        name="shortcode"
                                        class="form-control"
                                        type="text"
                                        value="{{ "{!" . "! forms($form->id) !" . "!}" }}"
                                        readonly
                                        data-select-all-contents
                                    />
                                </div>
                            @endif

                            <div class="form-group">
                                <label for="mailto">Mail To
                                    <small>(Separate multiple with ',')</small>
                                </label>
                                <input
                                    name="mailto"
                                    class="form-control"
                                    type="text"
                                    @if (isset($form->mailto)) value="{{ $form->mailto }}" @endif
                                    placeholder="{{ setting('forms.default_to_email') }}"
                                />
                            </div>

                            <div class="form-group">
                                <label for="layout">Layout</label>
                                <select class="form-control" name="layout" id="layout">
                                    @foreach($layouts as $layout)
                                        <option
                                            value="{{ $layout }}"
                                            @if (isset($form->layout) && $form->layout === $layout)
                                            selected="selected"
                                            @endif
                                        >
                                            {{ ucwords(str_replace(array('_', '-'), ' ', $layout)) }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="email_template">Email Template</label>
                                <select class="form-control" name="email_template" id="email_template">
                                    @foreach($emailTemplates as $emailTemplate)
                                        <option
                                            value="{{ $emailTemplate }}"
                                            @if (isset($form->email_template) && $form->email_template === $emailTemplate)
                                            selected="selected"
                                            @endif
                                        >
                                            {{ ucwords(str_replace(array('_', '-'), ' ', $emailTemplate)) }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="message_success">Success Message</label>
                                <input
                                    name="message_success"
                                    class="form-control"
                                    type="text"
                                    @if (!isset($form)) value="Success! Thanks for your enquiry." @endif
                                    @if (isset($form->message_success)) value="{{ $form->message_success }}" @endif
                                    placeholder="Thanks for your enquiry"
                                />
                            </div>

                            <div class="form-group">
                                <label for="hook">Event Hook
                                    <small>(Fires after form is submitted)</small>
                                </label>
                                <input name="hook" class="form-control" type="text"
                                       @if (isset($form->hook)) value="{{ $form->hook }}" @endif>
                            </div>

                            <button type="submit" class="btn btn-primary">
                                {{ __('voyager::generic.'.(isset($form->id) ? 'update' : 'add')) }}
                                {{ $dataType->display_name_singular }}
                            </button>
                        </form>
                    </div>
                </div>

                @if (isset($form))
                    <div class="panel panel-bordered panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="voyager-plus"></i> Add Field</h3>
                        </div> <!-- /.panel-heading -->

                        <div class="panel-body">
                            <form role="form" action="{{ route('voyager.inputs.store') }}" method="POST"
                                enctype="multipart/form-data">
                                {{ csrf_field() }}

                                <div class="form-group">
                                    <label for="type">Field Type</label>
                                    <select class="form-control" name="type" id="type">
                                        <option value="">-- Select --</option>
                                        @foreach (config('voyager-forms.available_inputs') as $key => $value)
                                            <option value="{{ $key }}">{{ $value }}</option>
                                        @endforeach
                                    </select>
                                </div> <!-- /.form-group -->

                                <input type="hidden" name="form_id" value="{{ $form->id }}"/>
                                <button type="submit"
                                        class="btn btn-success btn-sm">{{ __('voyager::generic.add') }}</button>
                            </form>
                        </div> <!-- /.panel-body -->
                    </div> <!-- /.panel -->
                @endif
            </div>

            <div class="col-md-8">
                @if (isset($form))
                    <div class="dd">
                        <ol class="dd-list">
                            @each('voyager-forms::inputs.edit-add', $form->inputs, 'input')
                        </ol>
                    </div> <!-- /.dd -->
                @endif
            </div>
        </div>
    </div>
@stop

@section('javascript')
    <script>
        $('document').ready(function () {
            $('.toggleswitch').bootstrapToggle();

            /**
             * Confirm DELETE input
             */
            $("[data-delete-input-btn]").on('click', function (e) {
                e.preventDefault();
                var result = confirm("Are you sure you want to delete this input?");
                if (result) $(this).closest('form').submit();
            });

            /**
             * Select all text on focus
             */
            $("[data-select-all-contents]").on("click", function () {
               $(this).select();
            });

            /**
             * ORDER Inputs
             */
             // Init drag 'n drop
            $('.dd').nestable({ handleClass: 'order-handle', maxDepth: 1 });

            // Close all panels when dragging
            $('.order-handle').on('mousedown', function() { $('.dd').addClass('dd-dragging'); });

            // Fire request when drag complete
            $('.dd').on('change', function (e) {
                // Only when it's a result of drag and drop
                // -- Otherwise this triggers on every form change within .dd
                if ($('.dd').hasClass('dd-dragging')) {
                    // And reopen panels once drag has finished
                    $('.dd').removeClass('dd-dragging');

                    // Post the request
                    $.post('{{ route('voyager.forms.sort') }}', {
                        order: JSON.stringify($('.dd').nestable('serialize')),
                        _token: '{{ csrf_token() }}'
                    }, function (data) {
                        toastr.success("Order saved");
                    });
                }
            });
        });
    </script>
@stop

resources/views/forms/render.blade.php
<form id="{{ $form->title }}" action="{{ route('voyager.enquiries.submit', ['id' => $form->id]) }}" method="POST" enctype="multipart/form-data">
    {{ csrf_field() }}

    @if (session('success'))
        <div class="callout success">{{ session('success') }}</div>
    @endif

    @php $groupCounter = 0; @endphp

    @foreach ($form->inputs as $input)
        @if ($input->type === 'group')
            @if ($groupCounter % 2 === 0)
                <span class="{{ $input->class }} groupedInputTitle"> {{ $input->label }}</span>
                <div class="{{ $input->class }} groupedInput"> 
            @else
                </div> 
            @endif
            @php $groupCounter++; @endphp
        @else

            <div class="{{ $input->class }}">
                @if (in_array($input->type, ['text', 'number', 'email']))
                    <label for="{{ $input->label }}">
                        {{ $input->label }}
                        <input name="{{ $input->label }}" type="{{ $input->type }}" @if ($input->required) required @endif>
                    </label>
                @endif

                @if ($input->type === 'text_area')
                    <label for="{{ $input->label }}">
                        {{ $input->label }}
                        <textarea name="{{ $input->label }}" @if ($input->required) required @endif></textarea>
                    </label>
                @endif

                @if ($input->type === 'select')
                    <label for="{{ $input->label }}">
                        {{ $input->label }}
                        <select name="{{ $input->label }}" @if ($input->required) required @endif>
                            <option value="">-- Select --</option>

                            @foreach (explode(', ', $input->options) as $option)
                                <option value="{{ $option }}">{{ $option }}</option>
                            @endforeach
                        </select>
                    </label>
                @endif

                @if (in_array($input->type, ['radio', 'checkbox']))
                    <fieldset class="fieldset medium-12 cell">
                        <legend>{{ $input->label }}</legend>
                        @foreach (explode(', ', $input->options) as $option)
                            <input
                                id="{{ $option }}-{{ $input->type }}"
                                name="{{ $input->label }}"
                                type="{{ $input->type }}"
                                value="{{ $option }}"
                            >
                            <label for="{{ $option }}-{{ $input->type }}">{{ ucwords($option) }}</label>
                        @endforeach
                    </fieldset>
                @endif

                @if ($input->type === 'file')
                    <label for="{{ $input->label }}">
                        {{ $input->label }}
                        <input type="file" name="{{ $input->label }}" accept="{{ $input->options }}" @if ($input->required) required @endif>
                    </label>
                @endif
                
                @error($input->label)
                    <div class="error">
                        {{$message}}
                    </div>
                @enderror
            </div>
        @endif
    @endforeach

    @if ($groupCounter % 2 === 1)
        </div>
    @endif

    @if (setting('admin.google_recaptcha_site_key'))
        <button
            class="button g-recaptcha"
            data-badge="inline"
            data-sitekey="{{ setting('admin.google_recaptcha_site_key') }}"
            data-callback="onSubmit" onclick="setFormId('{{ $form->title }}')"
        >
            @if($input->type === 'submit') 
                {{$input->label}}
            @else
                Submit
            @endif
        </button>
    @else
        <button class="button" id="submit" type="submit" value="submit">
            @if($input->type === 'submit') 
                {{$input->label}}
            @else
                Submit
            @endif
        </button>
    @endif
</form>

resources/views/layouts/default.blade.php
@include('voyager-forms::forms.render')